version: "3.9"

services:

  db:
    image: postgres:15
    container_name: pg-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8000:80"

    depends_on:
      - db

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main

    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"

    environment:
      - DEBUG=1
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - "/var/run/docker.sock:/var/run/docker.sock"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector

    command:
      - "--config=/etc/otelcol-contrib/config.yaml"

    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml

    ports:
      - "4317:4317"
      - "4318:4318"

volumes:
  postgres_data: