server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 100% of requests are traced
  otlp:
    tracing:
      # Explicitly disable the OTLP exporter
      endpoint: none
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs
